name: Build
on:
  workflow_dispatch:
permissions:
  contents: write
env:
  cache-version: v1.0.3

jobs:
  linux:
    name: build and test on Linux
    runs-on: ubuntu-latest
    steps:
      - name: set release date
        shell: bash
        run: |
          echo "RELEASE_DATE=$(date '+%Y%m%d%H%M%S')" >> ${GITHUB_ENV}

      - name: Checkout zetasql repository
        uses: actions/checkout@v4
        with:
          repository: 'google/zetasql'
          fetch-depth: 0
          
      - name: Checkout build patch
        run: |
          git clone https://github.com/hxbb00/zetasql-build.git _work_patch
  
      - name: copy patch
        run: |
          cp -rf _work_patch/*.sh .
        
      - name: Setup gcc-9
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y gcc-9 g++-9
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 900 \
            --slave /usr/bin/g++ g++ /usr/bin/g++-9

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 9123335

      - name: Setup Android SDK via sdkmanager
        run: |
          sdkmanager tools "platforms;android-30"
  
      - name: Setup Bazel
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 6.2.0
          
      - name: Use Bazel
        if: matrix.os != 'windows'
        run: bazel -h

      - name: build
        run: |
          chmod +x build_zetasql_parser.sh
          ./build_zetasql_parser.sh

      - name: pack libzetasql
        run: |
          chmod +x pack_zetasql.sh
          ./pack_zetasql.sh -d ubuntu
        env:
          TAG: ${{ env.RELEASE_DATE }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: libzetasql-*.tar.gz
          name: release-artifacts

  windows:
    name: build and test on windows
    runs-on: windows-latest
    steps:
      - name: set release date
        shell: bash
        run: |
          echo "RELEASE_DATE=$(date '+%Y%m%d%H%M%S')" >> ${GITHUB_ENV}

      - name: Checkout zetasql repository
        uses: actions/checkout@v4
        with:
          repository: 'google/zetasql'
          fetch-depth: 0
          
      - name: Checkout build patch
        shell: cmd
        run: |
          git clone https://github.com/hxbb00/zetasql-build.git C:\_work_patch
  
      - name: copy patch
        shell: bash
        run: |
          cp -rf C:/_work_patch/*.sh .

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 9123335

      - name: Setup Android SDK via sdkmanager
        run: |
          sdkmanager tools "platforms;android-30"
          
      - name: Setup Bazel
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 6.2.0
        
      - name: Use Bazel (Windows only)
        shell: bash
        run: bazel.exe -h

      - name: build
        shell: bash
        run: |
          ./build_zetasql_parser.sh
